name: Week 1
on:
  push:
    branches:
      - week1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)

      - name: Step 1
        if: ${{steps.vars.outputs.count == 0 && github.event.head_commit.message != 'Update progress'}}
        env:
          SUPER_SECRET: ${{ secrets.HTTP_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/testfirstfunction.js

      - name: Step 2
        if: ${{steps.vars.outputs.count == 1 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/test2.hello.js

